### ISSUE TITLE
MS not sent; to enable sending, set the TWILIO_CREDENTIALS environment variable

### ISSUE THREAD

**Issue by gg2001** [DAB0mB/angular-meteor-whatsapp#13]
Hi, 
Application looks great. However, I was getting this in my terminal when I inputted my phone number, and I didn't get an SMS. How exactly do I set the environment variable?
Thanks

**Comment by navi8602** [comment]
> 
If you would like to test the verification with a real phone number, accouts-phone provides an easy access for twilio's API, for more information see accounts-phone's repo.
>

**Comment by DAB0mB** [comment]
https://github.com/okland/accounts-phone

You need to set your config accordingly

**Comment by terajoellang** [comment]
@DAB0mB Could you please provide an example code, because if I visit [https://github.com/okland/accounts-phone](https://github.com/okland/accounts-phone), I can't see, where i have to set the TWILIO_CREDENTIALS Environment variable

It says:
If you are using twilio : you can just put your twilio credentials on server.

SMS.twilio = {FROM: 'XXXXXXXXXXXX', ACCOUNT_SID: 'XXXXXXXXXXXXXXXXXXXXX', AUTH_TOKEN: 'XXXXXXXXXXXXXXXXXXXX'};
 
But where do I have to enter this "SMS.twilio = {FROM: 'XXX..."?
In wich file?
