### ISSUE TITLE
This code doesn't work in production mode

### ISSUE THREAD

**Issue by marines** [DAB0mB/angular-meteor-whatsapp#18]
`meteor run --production` gives `Error: [ng:areq] Argument 'LoginCtrl' is not a function, got undefined` on every route change (with different controllers).

**Comment by juancho559** [comment]
Did you find something? I had the same issue!!

**Comment by marines** [comment]
It definitely has something with minification but I didn't investigate it further.

**Comment by juancho559** [comment]
Hi @marines 
You're right, and I found something. If you change the way that you reference controllers in routes.js file, everything starts working. This is my previous code:

controller: 'ProfileCtrl as profile',

And I changed this code for this one:
controller: ProfileCtrl 
controllerAs: 'profile',

Obviously, I have to reference the ProfileCtrl variable in the imports:
import ProfileCtrl from './controllers/profile.controller';

**Comment by marines** [comment]
Strange. I've tried that but it didn't work then. But it works now. Thanks!

**Comment by vivekmago** [comment]
I am still getting the issue.. could you clarify where you are add reference to profilectrl

**Comment by marines** [comment]
@vivekmago In the routes. Import a controller and reference it as a variable rather than a string.

**Comment by mncvnn** [comment]
Hi guys,
I've the same problem on Heroku, and after following your suggestion here, the InboxCtrl has been not an issue any more.
However, I used a service (as new-chat service) for login form, which has a LoginCtrl. At my local it worked perfect, but when I submitted to Heroku (even try on OpenShift), still got the same error:
> Error: [ng:areq] Argument 'LoginCtrl' is not a function, got undefined
> http://errors.angularjs.org/1.5.3/ng/areq?p0=LoginCtrl&p1=not%20aNaNunction%2C%20got%20undefined

Where should I declare it? It's a service, and even LoginCtrl not in the route.
I'm new to this, so basicly, I'm following steps here, just some twist to make my app different, to learn of-course.
In case you need, my login template look like this:

> <ion-modal-view ng-controller="LoginCtrl as logger">
>     <ion-header-bar>
>         <h1 class="title">Đăng nhập</h1>
>         <div class="buttons">
>             <button class="button button-clear" ng-click="logger.hideLoginModal()">Đóng</button>
>         </div>
>     </ion-header-bar>
>     <ion-content>
>         <form ng-submit="logger.doLogin()">
>         -------------------------- cut here -----------------------
>         </form>
>     </ion-content>
> </ion-modal-view>

**Comment by DAB0mB** [comment]
This is caused due to minification made in production mode.
As @juancho559 said, just import the controller instead of providing its name as a string

**Comment by mncvnn** [comment]
Hi @DAB0mB ,
Then where should I import it? This controller defined in html file.
I've tried import it to app.js, routes.js. Nothing work!

**Comment by DAB0mB** [comment]
```js
    import Controller from '../controller'
```

Like this.
Doesn't it work?

**Comment by mncvnn** [comment]
Hi @DAB0mB,
No, It doesn't work.

I have to user controller inside a new-chat.html like this:
> `<ion-modal-view` ng-controller="NewChatCtrl as chat">

And from @juancho559 post, this would cause problem and it's.

Right now, If I run my code locally, everything perfect, but after hosting to remove server, ONLY new-chat function not work.

**Comment by DAB0mB** [comment]
@mncvnn The `NewChatCtrl` is a different case since it is not used in any of the routes, it is used by the service. I think what happens is that the minification process changes the name of the `NewChatCtrl` function to something else, probably a single letter like `a`, or `b`. By default, if you don't provide a `$name` property to you controller then the default name is gonna be the name of the function, therefore the controller is not available. My suggestion is that you will define the name of the controller explicitly.

Inside the `new-chat.controller.js` file, right after the `NewChatCtrl` class is initialized, add the following line:

```js
    NewChatCtrl.$name = 'NewChatCtrl';
```

This should do the trick. Please tell me if it works so I will know if I can close this issue or not :-)

**Comment by mncvnn** [comment]
Hi @DAB0mB,
First of all, thank you very much for your great supported.
It works perfect now on both local and production (I hosted it in openshift, and I think it'd not an issue on heroku, sure).

And thank for your clear declaration, how and what went wrong, I'm a little bit more understand now. Since I came to this tutor without much knowledge of angular, still try to learn more and your post help me a lot more than any others.

Now you can close the issue.
Again, thanks.

**Comment by marines** [comment]
No you can't because the issue still exists.

**Comment by DAB0mB** [comment]
@marines Sorry I'm sure you solved it. Can you please add a `$name` to each controller and see if it works after minification?

**Comment by marines** [comment]
Sure I did but the code itself is still broken and that's what this issue is about.
