### ISSUE TITLE
is there any option to use accounts-password  instead of accounts-phone

### ISSUE THREAD

**Issue by naysumyat** [DAB0mB/angular-meteor-whatsapp#22]

**Comment by adammoisa** [comment]
I recently made a pull request to the okland:accounts-phone package which updates accounts-phone to depend on accounts-password and a newer bycrpt version. Once he merges,
[package.js.zip](https://github.com/DAB0mB/angular-meteor-whatsapp/files/420219/package.js.zip)

 I'd recommend using that package since it works well and offers text verification support.

Alternatively, if you don't want to wait, you can download his repo locally into a packages dir at the root level of your project, change the packages.js file as such. 

Package.onUse(function (api) {
    //api.use('npm-bcrypt@=0.7.8_2', 'server');
    ->api.use('npm-bcrypt@=0.8.7_1', 'server');

    //api.use('accounts-base@1.0.2', ['client', 'server']);
    ->api.use('accounts-password@1.2.14', ['client', 'server']);

    // Export Accounts (etc) to packages using this one.

    //api.imply('accounts-base@1.0.2', ['client', 'server']);
    ->api.imply('accounts-password@1.2.14', ['client', 'server']);

Then, add the local using meteor add accounts-phone' if you also changed the name on top to just accounts-phone instead of okland:accounts-phone. Feel free to just overwrite the file with the one I attached.

[package.js.zip](https://github.com/DAB0mB/angular-meteor-whatsapp/files/420223/package.js.zip)

**Comment by DAB0mB** [comment]
@adammoisa Thank you for your answer. @naysumyat In addition I suggest you go on StackOverflow http://stackoverflow.com/questions/tagged/meteor since this is not an issue.
