### ISSUE TITLE
Command 'meteor npm install ionic-scripts --save' gets this error

### ISSUE THREAD

**Issue by juliocesar12** [DAB0mB/angular-meteor-whatsapp#30]
Hello, I am following the tutotial of Whatssap Project with Meteor and Ionic(http://www.angular-meteor.com/tutorials/whatsapp/meteor/bootstrapping), but at the moment when I run the command 'meteor npm install ionic-scripts --save' I get this bug:

+-- UNMET PEER DEPENDENCY angular@^1.5.0
+-- UNMET PEER DEPENDENCY angular-animate@^1.4.3
+-- UNMET PEER DEPENDENCY angular-sanitize@^1.4.3
+-- UNMET PEER DEPENDENCY angular-ui-router@^0.2.13
`-- ionic-scripts@0.0.1

I don´t know if someone can help me, I will really appreciate it.
Thanks

**Comment by DAB0mB** [comment]
@juliocesar12 'Peer Dependencies' are dependencies whose existence are crucial otherwise the dependent package won't work, and they need to be loaded directly from your project! This is normal and you might encounter suck packages once in a while. To solve the issue, simply run the following: 

    $ npm install angular
    $ npm install angular-animate
    $ npm install angular-sanitize
    $ npm install angular-ui-router

I'm pretty certain that everything will work fine now, but just to make sure just give me your approval so I can close this issue :-)

**Comment by DAB0mB** [comment]
I will also update the tutorial as well, in the previous versions of npm peer dependencies were installed automatically but now this feature is no more.
